apiVersion: v2
name: atatus-agent
type: application
description: Official helm chart for Atatus Agent
version: 1.0.6
appVersion: 3.2.0
keywords:
  - atatus
  - observability
  - monitoring
  - logging
  - kubernetes
  - metrics
  - agent
maintainers:
  - name: Atatus
    email: success@atatus.com
home: https://www.atatus.com/
icon: https://www.atatus.com/images/logo/atatus-icon.png
dependencies:
  - name: "kube-state-metrics"
    version: "4.7.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: atatus.state_metrics.enabled
